# Generated by Django 3.2.13 on 2022-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='upvoteCount',
            field=models.IntegerField(default=0),
        ),
    ]
