version: '3'
services:
    dbos:
      image: postgres
      volumes:
         - postgres_storage:/var/lib/postgresql/data
      restart: always  #to keep the container running
      environment:
            POSTGRES_USER: manish
            POSTGRES_PASSWORD: manish
            POSTGRES_DB: mydb
      ports:
         - 5432:5432
    djos:
      image: django_os_five
      restart: always
      depends_on:  #(--link for linking to other container)
         - dbos
      ports:       # for exposing the container
         - 8000:8000
      environment:
            POSTGRES_USER: manish
            POSTGRES_PASSWORD: manish
            POSTGRES_DB: mydb

      volumes:      # to mount to the volume
         - django_storage:/home
volumes:
    django_storage:      #to first create the volumes
    postgres_storage:
